### ISSUE TITLE
How to use with a non-ts project within VSCode?

### ISSUE THREAD

**Issue by ersel** [segmentio/ts-mysql-plugin#5]
This looks like a great plugin, thanks for open-sourcing it.

Is it possible to use this project without a typescript codebase? Can we add a minimal `tsconfig.json` to our project root just to be able to make use of this plugin? Any help is appreciated.

**Comment by stevenmiller888** [comment]
I don't believe this is possible, as the TypeScript compiler only runs plugins on `.ts` files. I made an attempt by using the tsconfig options `"allowJs": true` and `"checkJs": true` but it didn't work.
